title: Chidinma Idonor
logo: /assets/img/headshot_circle.jpg
#description: text below image
show_downloads: false
# Custom additions
education:
  - degree: M.Sc. Electrical/Computer Engineering
    institution: The University of Tulsa
    year: 2025 - 2026
theme: jekyll-theme-minimal
